### ISSUE TITLE
手机号登录，get改post，云函数执行返回504错误

### ISSUE THREAD

**Issue by cooper1x** [wwxiaoqi/TencentNeteaseCloudPunch#1]
博主你好，我看了你的文章，大致思路了解，但有很多细节没有描述清楚。
我摸索了一段时间后，发现密码如果有特殊字符，get请求是无法成功的，会返回400。
而且php代码里面需要改的地方在Blog中也没有体现出来，Cron 表达式这样写的意图也不是很明确。
我有自己服务器，有宝塔面板PM2装node运行API接口，本地postman测试是OK的，但云函数一直都是504返回超时。
不知道你没有遇到过这个情况。

**Comment by wwxiaoqi** [comment]
你好，关于特殊字符的问题我没有碰到过。。
而关于 PHP 需要修改的地方主要是：
[修改内容](https://wwxiaoqi-1253423189.cos.ap-guangzhou.myqcloud.com/blog/Snipaste_2020-06-09_22-34-53.png)

Cron 表达式这样写的原因在这里：
https://cloud.tencent.com/document/product/1209/42675

**Comment by cooper1x** [comment]
@wwxiaoqi 感谢回复，这里我是这样配置的，而且是自己搭建好了API接口。
只是云函数执行后，总是返回：
```SHELL
Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 
```
而且腾讯云的相关参数也是空的，我想看看你那边成功是什么样的提示。
![image](https://user-images.githubusercontent.com/9080789/84218597-5950b580-ab01-11ea-82ce-5d0238f822fe.png)

**Comment by wwxiaoqi** [comment]
@cooper1x 
返回其 errorMessage 信息在提示你:  `用户进程在运行时退出了`
我想大概是你测试的时候刷新操作或者超时了吧~

且因为代码含有大量 for 循环操作，故需要把超时时间设置为 600 以上~

[超时时间](https://wwxiaoqi-1253423189.cos.ap-guangzhou.myqcloud.com/Github/%E8%B6%85%E6%97%B6%E6%97%B6%E9%97%B4.png)

[Success](https://wwxiaoqi-1253423189.cos.ap-guangzhou.myqcloud.com/Github/Success.png)

[HTTP](https://wwxiaoqi-1253423189.cos.ap-guangzhou.myqcloud.com/Github/com.png)

[Code](https://wwxiaoqi-1253423189.cos.ap-guangzhou.myqcloud.com/Github/code.png)

**Comment by cooper1x** [comment]
@wwxiaoqi 我把login这里改写了一下，主要是加了encode。
```
function login($username, $password)
{
    global $localurl;
    $url = $localurl . "/login/cellphone?phone={$username}&password={$password}";
    $data = getcurl(urlencode($url), 0, 1);
    if (preg_match_all('/Set-Cookie:(.*);/iU', $data, $str) == 0) {
        die($data);
    }
    $cookies = $str[1][0] . ";" . $str[1][1] . ";" . $str[1][2] . ";";
    return $cookies;
}
```
超时的时间我设置600ms了，这个没问题，我再试试公共api。

**Comment by cooper1x** [comment]
密码改了就好了，估计接口还是有点问题，但每天打卡300首没有满
